swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/{userId}/transactions:
    get:
      tags:
        - Transaction Module
      summary:  Transactions by user
      description: API for getting all transactions associated with a user
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: userId
          description: Id of the user
          required: true
          type: 'string'
      responses:
        '200':
          description: List of resource retrieved Successfully
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Parameters
        '401':
          description: Unauthenticated user
        '404':
          description: User not found
        '500':
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      tags:
        - Details transaction Module
      summary:  Details of one transaction
      description: API for getting details a specific transactions associated with a user
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: Id of the transaction
          required: true
          type: 'string'
      responses:
        '200':
          description: resource retrieved Successfully
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/TransactionDetailsResponse'
        '400':
          description: Invalid Parameters
        '401':
          description: Unauthenticated user
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Modify transaction Module
      summary: Modify one transaction
      description: API to modify a specific transaction associated with a user
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: Id of the transaction
          required: true
          type: string
      responses:
        '200':
          description: Resource updated successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/TransactionDetailsResponse'
        '400':
          description: Invalid Parameters
        '401':
          description: Unauthenticated user
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Delete transaction Module
      summary:  Delete of one transaction
      description: API to delete of specific transactions associated with a user
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: Id of the transaction to delete
          type: 'string'
          required: true
      responses:
        '204':
          description: resource deleted successfully
        '400':
          description: Invalid Parameters
        '401':
          description: Unauthenticated user
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /transactions:
    post:
      tags:
        - Add transaction Module
      summary: Add transaction
      description: API for adding a transaction associated with a user
      security: 
        - Bearer: []
      parameters:
        - in: body
          name: body
          description: Details of the transaction to add.
          required: true
          schema:
            $ref: '#/definitions/TransactionDetailsRequest'
      responses:
        '201':
          description: Resource added successfully
          schema:
            $ref: '#/definitions/TransactionDetailsResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthenticated user
        '404':
          description: User not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionDetailsResponse:
    type: object
    properties:
      id:
        type: number
        description: Unique identifier for the transaction
      email:
        type: string
        description: Email of the user associated with the transaction
      title:
        type: string
        description: Title or description of the transaction
      amount:
        type: string
        description: Amount of the transaction, formatted as a string (e.g., "$2,082.79")

  TransactionDetailsRequest:
    type: object
    required:
      - title
      - amount
    properties:
      title:
        type: string
        description: Title or description of the transaction
      amount:
        type: string
        description: Amount of the transaction, formatted as a string (e.g., "$2,082.79")
      email:
        type: string
        description: Email of the user associated with the transaction
